# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DGS.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 708)
        font = QtGui.QFont()
        font.setPointSize(24)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title_Label = QtWidgets.QLabel(self.centralwidget)
        self.Title_Label.setGeometry(QtCore.QRect(60, 10, 581, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label.setFont(font)
        self.Title_Label.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label.setObjectName("Title_Label")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(310, 630, 83, 50))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(28)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("color: rgb(108, 108, 108);")
        self.quitButton.setObjectName("quitButton")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(70, 100, 571, 491))
        self.Tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tabs.setStyleSheet("color: rgb(218, 145, 0);")
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Tabs.setElideMode(QtCore.Qt.ElideNone)
        self.Tabs.setTabsClosable(False)
        self.Tabs.setMovable(False)
        self.Tabs.setTabBarAutoHide(False)
        self.Tabs.setObjectName("Tabs")
        self.outputTab = QtWidgets.QWidget()
        self.outputTab.setObjectName("outputTab")
        self.ListWidget = QtWidgets.QListWidget(self.outputTab)
        self.ListWidget.setEnabled(True)
        self.ListWidget.setGeometry(QtCore.QRect(20, 10, 531, 381))
        self.ListWidget.setStyleSheet("font: 57 18pt \"Ubuntu\";\n"
"color: rgb(156, 156, 156);")
        self.ListWidget.setObjectName("ListWidget")
        self.viewPurchasesBtn = QtWidgets.QPushButton(self.outputTab)
        self.viewPurchasesBtn.setGeometry(QtCore.QRect(180, 400, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setItalic(True)
        self.viewPurchasesBtn.setFont(font)
        self.viewPurchasesBtn.setStyleSheet("color: rgb(108, 108, 108);")
        self.viewPurchasesBtn.setObjectName("viewPurchasesBtn")
        self.Tabs.addTab(self.outputTab, "")
        self.newCustomerTab = QtWidgets.QWidget()
        self.newCustomerTab.setObjectName("newCustomerTab")
        self.addCustomerBtn = QtWidgets.QPushButton(self.newCustomerTab)
        self.addCustomerBtn.setGeometry(QtCore.QRect(220, 350, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setItalic(True)
        self.addCustomerBtn.setFont(font)
        self.addCustomerBtn.setStyleSheet("color: rgb(108, 108, 108);")
        self.addCustomerBtn.setObjectName("addCustomerBtn")
        self.Title_Label_2 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_2.setGeometry(QtCore.QRect(60, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_2.setFont(font)
        self.Title_Label_2.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_2.setObjectName("Title_Label_2")
        self.firstNameText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.firstNameText.setGeometry(QtCore.QRect(220, 40, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.firstNameText.setFont(font)
        self.firstNameText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.firstNameText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.firstNameText.setReadOnly(False)
        self.firstNameText.setObjectName("firstNameText")
        self.lastNameText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.lastNameText.setGeometry(QtCore.QRect(220, 90, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.lastNameText.setFont(font)
        self.lastNameText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lastNameText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.lastNameText.setReadOnly(False)
        self.lastNameText.setObjectName("lastNameText")
        self.Title_Label_3 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_3.setGeometry(QtCore.QRect(60, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_3.setFont(font)
        self.Title_Label_3.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_3.setObjectName("Title_Label_3")
        self.Title_Label_4 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_4.setGeometry(QtCore.QRect(60, 140, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_4.setFont(font)
        self.Title_Label_4.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_4.setObjectName("Title_Label_4")
        self.addressText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.addressText.setGeometry(QtCore.QRect(220, 140, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.addressText.setFont(font)
        self.addressText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.addressText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.addressText.setReadOnly(False)
        self.addressText.setObjectName("addressText")
        self.cityText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.cityText.setGeometry(QtCore.QRect(140, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.cityText.setFont(font)
        self.cityText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cityText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.cityText.setReadOnly(False)
        self.cityText.setObjectName("cityText")
        self.Title_Label_5 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_5.setGeometry(QtCore.QRect(30, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_5.setFont(font)
        self.Title_Label_5.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_5.setObjectName("Title_Label_5")
        self.Title_Label_6 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_6.setGeometry(QtCore.QRect(230, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_6.setFont(font)
        self.Title_Label_6.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_6.setObjectName("Title_Label_6")
        self.stateText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.stateText.setGeometry(QtCore.QRect(340, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.stateText.setFont(font)
        self.stateText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.stateText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.stateText.setReadOnly(False)
        self.stateText.setObjectName("stateText")
        self.zipText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.zipText.setGeometry(QtCore.QRect(450, 190, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.zipText.setFont(font)
        self.zipText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.zipText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.zipText.setReadOnly(False)
        self.zipText.setObjectName("zipText")
        self.Title_Label_7 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_7.setGeometry(QtCore.QRect(350, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_7.setFont(font)
        self.Title_Label_7.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_7.setObjectName("Title_Label_7")
        self.Title_Label_8 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_8.setGeometry(QtCore.QRect(70, 250, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_8.setFont(font)
        self.Title_Label_8.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_8.setObjectName("Title_Label_8")
        self.emailText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.emailText.setGeometry(QtCore.QRect(210, 250, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.emailText.setFont(font)
        self.emailText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.emailText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.emailText.setReadOnly(False)
        self.emailText.setObjectName("emailText")
        self.Title_Label_9 = QtWidgets.QLabel(self.newCustomerTab)
        self.Title_Label_9.setGeometry(QtCore.QRect(70, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_9.setFont(font)
        self.Title_Label_9.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_9.setObjectName("Title_Label_9")
        self.phoneText = QtWidgets.QTextBrowser(self.newCustomerTab)
        self.phoneText.setGeometry(QtCore.QRect(210, 300, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.phoneText.setFont(font)
        self.phoneText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.phoneText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.phoneText.setReadOnly(False)
        self.phoneText.setObjectName("phoneText")
        self.statusLabel = QtWidgets.QLabel(self.newCustomerTab)
        self.statusLabel.setGeometry(QtCore.QRect(40, 410, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("color: rgb(130, 130, 130);")
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.Title_Label_7.raise_()
        self.zipText.raise_()
        self.addCustomerBtn.raise_()
        self.Title_Label_2.raise_()
        self.firstNameText.raise_()
        self.lastNameText.raise_()
        self.Title_Label_3.raise_()
        self.Title_Label_4.raise_()
        self.addressText.raise_()
        self.Title_Label_5.raise_()
        self.Title_Label_6.raise_()
        self.stateText.raise_()
        self.cityText.raise_()
        self.Title_Label_8.raise_()
        self.emailText.raise_()
        self.Title_Label_9.raise_()
        self.phoneText.raise_()
        self.statusLabel.raise_()
        self.Tabs.addTab(self.newCustomerTab, "")
        self.viewCustomerDataTab = QtWidgets.QWidget()
        self.viewCustomerDataTab.setObjectName("viewCustomerDataTab")
        self.retrieveDataBtn = QtWidgets.QPushButton(self.viewCustomerDataTab)
        self.retrieveDataBtn.setGeometry(QtCore.QRect(210, 200, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setItalic(True)
        self.retrieveDataBtn.setFont(font)
        self.retrieveDataBtn.setStyleSheet("color: rgb(108, 108, 108);")
        self.retrieveDataBtn.setObjectName("retrieveDataBtn")
        self.statusLabel2 = QtWidgets.QLabel(self.viewCustomerDataTab)
        self.statusLabel2.setGeometry(QtCore.QRect(20, 280, 521, 101))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel2.setFont(font)
        self.statusLabel2.setStyleSheet("color: rgb(130, 130, 130);")
        self.statusLabel2.setText("")
        self.statusLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel2.setObjectName("statusLabel2")
        self.Title_Label_12 = QtWidgets.QLabel(self.viewCustomerDataTab)
        self.Title_Label_12.setGeometry(QtCore.QRect(110, 110, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label_12.setFont(font)
        self.Title_Label_12.setStyleSheet("color: rgb(130, 130, 130);")
        self.Title_Label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label_12.setObjectName("Title_Label_12")
        self.customerByIDText = QtWidgets.QTextBrowser(self.viewCustomerDataTab)
        self.customerByIDText.setGeometry(QtCore.QRect(240, 150, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(True)
        self.customerByIDText.setFont(font)
        self.customerByIDText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.customerByIDText.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(100, 100, 100);")
        self.customerByIDText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.customerByIDText.setReadOnly(False)
        self.customerByIDText.setObjectName("customerByIDText")
        self.Tabs.addTab(self.viewCustomerDataTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(2)
        self.quitButton.pressed.connect(MainWindow.close)
        self.customerByIDText.textChanged.connect(self.statusLabel2.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DGS, LLC"))
        self.Title_Label.setText(_translate("MainWindow", "DGS,LLC"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.viewPurchasesBtn.setText(_translate("MainWindow", "View Purchase History"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.outputTab), _translate("MainWindow", "Output"))
        self.addCustomerBtn.setText(_translate("MainWindow", "Add Customer"))
        self.Title_Label_2.setText(_translate("MainWindow", "First Name:"))
        self.Title_Label_3.setText(_translate("MainWindow", "Last Name:"))
        self.Title_Label_4.setText(_translate("MainWindow", "Address:"))
        self.Title_Label_5.setText(_translate("MainWindow", "City:"))
        self.Title_Label_6.setText(_translate("MainWindow", "State:"))
        self.Title_Label_7.setText(_translate("MainWindow", "ZIP:"))
        self.Title_Label_8.setText(_translate("MainWindow", "Email:"))
        self.Title_Label_9.setText(_translate("MainWindow", "Phone:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.newCustomerTab), _translate("MainWindow", "New Customer"))
        self.retrieveDataBtn.setText(_translate("MainWindow", "Retrieve Data"))
        self.Title_Label_12.setText(_translate("MainWindow", "Customer by ID"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.viewCustomerDataTab), _translate("MainWindow", "Customer Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
